#import "./fragments/DesignerLightFragment.gql"
#import "./fragments/FaqFragment.gql"
#import "./fragments/ProductLightFragment.gql"
#import "./fragments/ProjectLightFragment.gql"
#import "./fragments/NewsFragment"
#import "./fragments/StaffFragment"

query SiteSearch(
	$productIds: [ItemId]
	$designerIds: [ItemId]
	$faqIds: [ItemId]
	$newsIds: [ItemId]
	$projectIds: [ItemId]
	$staffIds: [ItemId]
	$first: IntType = 100
) {
	products: allProducts(first: $first, filter: { id: { in: $productIds } }) {
		...ProductLightFragment
	}
	designers: allDesigners(first: $first, filter: { id: { in: $designerIds } }) {
		...DesignerLightFragment
	}
	projects: allProjects(first: $first, filter: { id: { in: $projectIds } }) {
		...ProjectLightFragment
	}
	faqs: allFaqs(first: $first, filter: { id: { in: $faqIds } }) {
		...FaqFragment
	}
	news: allNews(first: $first, filter: { id: { in: $newsIds } }) {
		...NewsFragment
	}
	people: allStaffs(first: $first, filter: { id: { in: $staffIds } }) {
		...StaffFragment
	}
}
