fragment ShopifyProductFragment on Product { 
  id
  handle
  title
  
  variants (first: 10){
    edges{
      node{
        id
        title
        price {
          amount
        }
        
        weight
        availableForSale   
      }
    }
  } 
}