#import "./ImageFragment.gql"
#import "./SEOFragment.gql"

fragment DesignerFragment on DesignerRecord {
	id
	name
	image {
		...ImageFragment
	}
	description
	slug
	_seoMetaTags {
		...SEOFragment
	}
}
