fragment ImageMediumFragment on FileField {
	id
	mimeType
	url
	title
	responsiveImage(
		imgixParams: { w: 1600, auto: format }
		sizes: "(max-width: 46.24em) 100vw, 50vw"
	) {
		alt
		aspectRatio
		base64
		bgColor
		height
		sizes
		src
		srcSet
		webpSrcSet
		title
		width
	}
}
