#import "./ImageFragment.gql"
#import "./SEOFragment.gql"

fragment NewsFragment on NewsRecord {
	__typename
	id
	image {
		...ImageFragment
	}
	link
	linkText
	text(markdown: false)
	title
	slug
	createdAt
	_seoMetaTags {
		...SEOFragment
	}
}
