#import './ImageFragment.gql'
#import './ThumbnailFragment.gql'

fragment ProductLightFragment on ProductRecord{
  id
  title
  slug
  markAsNew
  family{
    id
    name
  }
  categories{
    id
    name
    namePlural
    position
  }
  image{
    ...ThumbnailFragment
  }
  environmentImage{
    ...ThumbnailFragment
  }
  designer{
    id
    name
    slug
  }
}