fragment ProductLightFragment on ProductRecord{
  id
  title
  slug
  family{
    id
    name
  }
  categories{
    id
    name
    namePlural
    position
  }
  image{
    ...ImageFragment
  }
  environmentImage{
    ...ImageFragment
  }
  designer{
    id
    name
    slug
  }
}