#import "./ImageFragment.gql"
#import "./FileFragment.gql"

fragment ProductFragment on ProductRecord{
  id
  title
  description (markdown:false)
  slug
  bimLink
  presentation
  markAsNew
  image {
    ...ImageFragment
  }
  productGallery {
    ... on FullwidthImageRecord {
      __typename
      id
      image{
        ...ImageFragment
      }      
    }
    ... on ImageGalleryRecord {
      __typename
      id
      gallery {
        ...ImageFragment
      }
    }
    ... on TextRecord {
      __typename
      id
      text(markdown: false)
    }
    ... on TwoColumnImageRecord {
      __typename
      id
      firstImage {
        ...ImageFragment
      }
      lastImage {
        ...ImageFragment
      }
    }
    ... on VideoRecord {
      __typename
      id
      video {
        ...ImageFragment
      }
    }
  }
  environmentImage{
    ...ImageFragment
  }
  colorImages {
    ...ImageFragment
  }
  family{
    id
    name
  }
  categories{
    id
    name
    position
  }
  connection {
    id
    name
  }
  designer {
    id
    name
  }
  dimmable {
    id
    name
  }
  electricalData {
    id
    name
  }
  electricalData {
    id
    name
  }
  lightFile {
    ...FileFragment
  }
  models {
    id
    name {
      id
      name
    }
    drawing {
      ...ImageFragment
    }
    lightsources {
      id
      included
      amount
      optional
      lightsource {
        id
        name
        price
        articleNo
      }
    }
    variants {
      color {
        id
        name
      }
      id
      material {
        id
        name
      }
      price
      volume
      weight
      feature{
        name
      }
      articleNo
    }
    accessories {
      articleNo
      price
      accessory {
        name
      }
    } 
  }
  mounting {
    id
    name
  }
  pdfFile {
    ...FileFragment
  }
  sockets {
    id
    name
  }
  seo: _seoMetaTags {
    attributes
    content
    tag
  }
}