#import "./ImageFragment.gql"
#import "./ProductFragment.gql"

fragment ProjectFragment on ProjectRecord{
  id
  location
  title
  slug
  projectType {
    id
    title
    titlePlural
  }
  image {
    ...ImageFragment
  }
  secondaryImage {
    ...ImageFragment
  }
  relatedProducts{
    ...ProductFragment
  }
  gallery {
    ... on FullwidthImageRecord {
      __typename
      id
      image {
        ...ImageFragment
      }
    }
    ... on ImageGalleryRecord {
      __typename
      id
      gallery {
        ...ImageFragment
      }
    }
    ... on TextRecord {
      __typename
      id
      text {
        value
        links {
          __typename  
          ... on ProductRecord{
            id
            title
            slug
          }
          ... on DesignerRecord{
            id
            name
            slug
          }
          ... on ProjectRecord{
            id
            title
            slug
          }
        }
      }
    }
    ... on TwoColumnImageRecord {
      __typename
      id
      firstImage {
        ...ImageFragment
      }
      lastImage {
        ...ImageFragment
      }
    }
    ... on VideoRecord {
      __typename
      id
      video {
        ...ImageFragment
      }
    }
  }
}