#import "./ImageFragment.gql"

fragment ProjectLightFragment on ProjectRecord{
  id
  location
  title
  slug
  projectType {
    id
    title
    titlePlural
  }
  image {
    ...ImageFragment
  }
  secondaryImage {
    ...ImageFragment
  }
}