#import "./fragments/ImageFragment.gql"
#import "./fragments/VideoFragment.gql"
#import "./fragments/NewsFragment.gql"

query Sustainability {
  sustainability {
    id
    title
    intro(markdown:false)
    image{
      ...ImageFragment
    }
    steps{
      ... on SustainabilityStepRecord{
        title
        text(markdown:false)
        image{
          ...ImageFragment
        }
        fullWidthImage
      }
    }
  }
}

query About {
  about {
    id
    intro(markdown: false)
    title
    image{
      ...ImageFragment
    }
    sections {
      id
      text
      image {
        ...ImageFragment
      }
      video {
        ...VideoFragment
      }
    }
  }
}

query News($slug:String){
  news(filter: {slug: { eq: $slug }}) {
    ...NewsFragment
  }
}

query LastNews {
  lastNews: allNews(orderBy: [createdAt_ASC], first: 1) {
    ...NewsFragment
  }
}

query AllNews($first: IntType = 5, $skip: IntType = 0){
  news: allNews(first: $first, skip: $skip) {
    ...NewsFragment
  }
  pagination: _allNewsMeta {
    count
  }
}

query Job($id:ItemId){
  job(filter:{id:{eq:$id}}) {
    id
    summary(markdown: false)
    text(markdown: false)
    title
  }
}

query AllJobs {
  jobs: allJobs {
    id
    summary(markdown: false)
    text(markdown: false)
    title
  }
}

query Press($id:ItemId){
  press(filter:{id:{eq:$id}}) {
    id
    title
    url
  }
}

query AllPress {
  presses: allPresses {
    id
    title
    url
  }
}
