query Sustainability {
	sustainability {
		id
		title
		intro(markdown: false)
		image {
			...ImageFragment
		}
		steps {
			... on SustainabilityStepRecord {
				title
				text(markdown: false)
				media {
					...VideoFragment
				}
				fullWidthImage
			}
		}
	}
}

query About {
	about {
		id
		intro(markdown: false)
		title(markdown: false)
		video {
			...VideoFragment
		}
		sections {
			id
			text
			video {
				...VideoFragment
			}
		}
	}
}

query News($slug: String) {
	news(filter: { slug: { eq: $slug } }) {
		...NewsFragment
	}
}

query LastNews {
	lastNews: allNews(orderBy: [createdAt_DESC], first: 1) {
		...NewsFragment
	}
}

query AllNews($first: IntType = 5, $skip: IntType = 0) {
	news: allNews(orderBy: [createdAt_DESC], first: $first, skip: $skip) {
		...NewsFragment
	}
	pagination: _allNewsMeta {
		count
	}
}

fragment NewsFragment on NewsRecord {
	__typename
	id
	image {
		...ImageFragment
	}
	link
	linkText
	text(markdown: false)
	title
	slug
	createdAt
	_seoMetaTags {
		...SEOFragment
	}
}

query Job($id: ItemId) {
	job(filter: { id: { eq: $id } }) {
		id
		summary(markdown: false)
		text(markdown: false)
		title
	}
}

query AllJobs($first: IntType = 100) {
	jobs: allJobs(first: $first) {
		id
		summary(markdown: false)
		text(markdown: false)
		title
	}
}

query Press($id: ItemId) {
	press(filter: { id: { eq: $id } }) {
		id
		title
		url
	}
}

query AllPress($first: IntType = 100) {
	presses: allPresses(first: $first) {
		id
		title
		url
	}
}
