#import "./fragments/ShowroomFragment.gql"
#import "./fragments/ContactFragment.gql"
#import "./fragments/DistributorFragment.gql"
#import "./fragments/ResellerFragment.gql"
#import "./fragments/StaffFragment.gql"
#import "./fragments/ImageFragment.gql"

query GetAllContact {
  contacts : allContacts {
    ...ContactFragment
  }
}

query GetShowroom {
  showroom {
    ...ShowroomFragment
  }
}

query GetAllShowrooms {
  showrooms: allShowrooms {
    ...ShowroomFragment
  }
}

query GetDistributor($id: ItemId, $locale: SiteLocale = en) {
	distributor(locale: $locale, fallbackLocales: [sv, en], filter: {id: { eq: $id }}) {
		...DistributorFragment
	}
}

query GetAllDistributors($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	distributors: allDistributors(first: $first, skip: $skip, orderBy: [name_ASC], locale: $locale, fallbackLocales: [sv, en]) {
		...DistributorFragment
	}
}

query GetReseller($id: ItemId, $locale: SiteLocale = en) {
	reseller(locale: $locale, fallbackLocales: [sv, en], filter: {id: { eq: $id }}) {
		...ResellerFragment
	}
}

query GetAllResellers($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	resellers: allResellers(first: $first, skip: $skip, orderBy: [name_ASC], locale: $locale, fallbackLocales: [sv, en]) {
		...ResellerFragment
	}
}

query GetStaff($id: ItemId, $locale: SiteLocale = en) {
	staff(locale: $locale, fallbackLocales: [sv, en], filter: {id: { eq: $id }}) {
		...StaffFragment
	}
}

query GetAllStaffs($id: ItemId, $locale: SiteLocale = en) {
	staffs : allStaffs(locale: $locale, fallbackLocales: [sv, en], filter: {id: { eq: $id }}) {
		...StaffFragment
	}
}

query GetContact{
	contact {
    id
    email
    intro(markdown: false)
    phone
    showroomIntro(markdown: false)
    title
    address
		image{
			...ImageFragment
		}
  }
}