#import "./fragments/ShowroomFragment.gql"
#import "./fragments/ContactFragment.gql"
#import "./fragments/DistributorFragment.gql"
#import "./fragments/ResellerFragment.gql"
#import "./fragments/StaffFragment.gql"
#import "./fragments/ImageFragment.gql"

query Showroom {
  showroom {
    ...ShowroomFragment
  }
}

query AllShowrooms {
  showrooms: allShowrooms {
    ...ShowroomFragment
  }
}

query Distributor($id: ItemId, $locale: SiteLocale = en) {
	distributor(locale: $locale, fallbackLocales: [sv, en], filter: {id: { eq: $id }}) {
		...DistributorFragment
	}
}

query AllDistributors($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	distributors: allDistributors(first: $first, skip: $skip, orderBy: [name_ASC], locale: $locale, fallbackLocales: [sv, en]) {
		...DistributorFragment
	}
}

query Reseller($id: ItemId, $locale: SiteLocale = en) {
	reseller(locale: $locale, fallbackLocales: [sv, en], filter: {id: { eq: $id }}) {
		...ResellerFragment
	}
}

query AllResellers($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	resellers: allResellers(first: $first, skip: $skip, orderBy: [name_ASC], locale: $locale, fallbackLocales: [sv, en]) {
		...ResellerFragment
	}
}

query Staff($id: ItemId, $locale: SiteLocale = en) {
	staff(locale: $locale, fallbackLocales: [sv, en], filter: {id: { eq: $id }}) {
		...StaffFragment
	}
}

query AllStaffs($id: ItemId, $locale: SiteLocale = en, $first: IntType = 100) {
	staffs : allStaffs(first: $first, locale: $locale, fallbackLocales: [sv, en], filter: {id: { eq: $id }}) {
		...StaffFragment
	}
}

query Contact{
	contact {
    id
    email
    intro(markdown: false)
    phone
    showroomIntro(markdown: false)
    title
    address
		image{
			...ImageFragment
		}
  }
}