query Showroom {
	showroom {
		...ShowroomFragment
	}
}

query AllShowrooms($first: IntType = 100, $skip: IntType = 0) {
	allShowrooms(first: $first, skip: $skip) {
		...ShowroomFragment
	}
	_allShowroomsMeta {
		count
	}
}

query Distributor($id: ItemId, $locale: SiteLocale = en) {
	distributor(locale: $locale, fallbackLocales: [sv, en], filter: { id: { eq: $id } }) {
		...DistributorFragment
	}
}

query AllDistributors($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	allDistributors(first: $first, skip: $skip, orderBy: [name_ASC], locale: $locale, fallbackLocales: [sv, en]) {
		...DistributorFragment
	}
	_allDistributorsMeta(locale: $locale, fallbackLocales: [sv, en]) {
		count
	}
}

fragment DistributorFragment on DistributorRecord {
	name
	address
	postalCode
	city
	country {
		name
	}
	contactName
	phone
	email
	url
}

fragment DistributorFragment on DistributorRecord {
	name
	address
	postalCode
	city
	country {
		name
	}
	contactName
	phone
	email
	url
}

query Reseller($id: ItemId, $locale: SiteLocale = en) {
	reseller(locale: $locale, fallbackLocales: [sv, en], filter: { id: { eq: $id } }) {
		...ResellerFragment
	}
}

query AllResellers($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	allResellers(first: $first, skip: $skip, orderBy: [name_ASC], locale: $locale, fallbackLocales: [sv, en]) {
		...ResellerFragment
	}
	_allResellersMeta(locale: $locale, fallbackLocales: [sv, en]) {
		count
	}
}

query Staff($id: ItemId, $locale: SiteLocale = en) {
	staff(locale: $locale, fallbackLocales: [sv, en], filter: { id: { eq: $id } }) {
		...StaffFragment
	}
}

query AllStaffs($first: IntType = 100, $skip: IntType = 0, $id: ItemId, $locale: SiteLocale = en) {
	allStaffs(first: $first, skip: $skip, locale: $locale, fallbackLocales: [sv, en], filter: { id: { eq: $id } }) {
		...StaffFragment
	}
	_allStaffsMeta(locale: $locale, fallbackLocales: [sv, en], filter: { id: { eq: $id } }) {
		count
	}
}

query Contact {
	contact {
		id
		email
		intro(markdown: false)
		phone
		showroomIntro(markdown: false)
		contactFormMessage(markdown: false)
		title
		address
		image {
			...ImageFragment
		}
	}
}

fragment ContactFragment on ContactRecord {
	address(markdown: false)
	email
	id
	intro(markdown: false)
	phone
	showroomIntro(markdown: false)
	title
}

fragment ResellerFragment on ResellerRecord {
	id
	name
	address
	postalCode
	city
	country {
		id
		name
	}
	url
}

fragment ShowroomFragment on ShowroomRecord {
	additional(markdown: false)
	address(markdown: false)
	city
	id
	image {
		...ImageMediumFragment
	}
}

fragment StaffFragment on StaffRecord {
	id
	name
	image {
		...ImageThumbnailFragment
	}
	role
	phone
	email
}
