query Designer($slug: String, $locale: SiteLocale = sv) {
	designer(locale: $locale, fallbackLocales: [sv, en], filter: { slug: { eq: $slug } }) {
		...DesignerFragment
	}
}

query AllDesigners($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = sv) {
	allDesigners(
		first: $first
		skip: $skip
		orderBy: [name_ASC]
		locale: $locale
		fallbackLocales: [sv, en]
	) {
		...DesignerLightFragment
	}
	_allDesignersMeta {
		count
	}
}

fragment DesignerFragment on DesignerRecord {
	__typename
	id
	name
	image {
		...ImageMediumFragment
	}
	description
	slug
	_seoMetaTags {
		...SEOFragment
	}
}

fragment DesignerLightFragment on DesignerRecord {
	__typename
	id
	name
	image {
		...ImageThumbnailFragment
	}
	description
	slug
}
