#import "./fragments/DistributorFragment.gql"

query GetDistributor($id: ItemId, $locale: SiteLocale = en) {
	distributor(locale: $locale, fallbackLocales: [sv, en], filter: {id: { eq: $id }}) {
		...DistributorFragment
	}
}

query GetAllDistributors($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	distributors: allDistributors(first: $first, skip: $skip, orderBy: [name_ASC], locale: $locale, fallbackLocales: [sv, en]) {
		...DistributorFragment
	}
}