#import "./fragments/ImageFragment.gql"
#import "./fragments/ProductFragment.gql"

query GetProductStart {
  productStart {
    id
    featured {
      headline
      items {
        ...ProductFragment
      }
    }
  }
  
}