#import "./fragments/SiteFragment.gql"

query Global {
  site: _site {
		...SiteFragment
	}
	allDesigners(first: 100, orderBy: [name_ASC]){
    id
    slug
    name
  }
  allProducts(first: 100){
    id
    designer{
      id
    }
  }
  allProductCategories{
    id
    namePlural
  }
}