// @ts-nocheck
export { GetDesigner, GetAllDesigners } from './designer.gql'
export { GetDistributor, GetAllDistributors } from './distributor.gql'
export { GetEmployee, GetAllEmployees } from './employee.gql'
export { GetGlobal } from './global.gql'
export { GetIntl } from './intl.gql'
export { GetNews, GetLastNews, GetAllNews } from './news.gql'
export { GetProduct, GetAllProducts, GetAllProductsLight, GetProductStart, GetProductCategories, GetAllProductsByDesigner } from './product.gql'
export { GetProject, GetAllProjects, GetProjectStart, GetAllProjectTypes, GetBespoke, GetDownload, GetFactoryVisit, GetAllFactoryVisits, GetAllDownloads } from './professional.gql'
export { GetReseller, GetAllResellers } from './reseller.gql'
export { GetSiteSEO } from './seo.gql'
export { GetStart } from './start.gql'
export { GetTaxonomy } from './taxonomy.gql'