// @ts-nocheck
export { GetSustainability, GetAbout, GetNews, GetLastNews, GetAllNews, GetJob, GetAllJob, GetPress, GetAllPress } from './about.gql'
export { GetContact, GetAllContact, GetShowroom, GetAllShowrooms, GetDistributor, GetAllDistributors, GetReseller, GetAllResellers, GetEmployee, GetAllEmployees } from './contact.gql'
export { GetDesigner, GetAllDesigners } from './designer.gql'
export { GetGlobal } from './global.gql'
export { GetIntl } from './intl.gql'
export { GetProduct, GetAllProducts, GetAllProductsLight, GetProductStart, GetProductCategories, GetAllProductsByDesigner } from './product.gql'
export { GetProject, GetAllProjects, GetProjectStart, GetAllProjectTypes, GetBespoke, GetDownload, GetFactoryVisit, GetAllFactoryVisits, GetAllDownloads } from './professional.gql'
export { GetSiteSEO } from './seo.gql'
export { GetStart } from './start.gql'
export { GetFAQ, GetAllFAQCategories, GetFAQStart, GetManual } from './support.gql'
export { GetTaxonomy } from './taxonomy.gql'