export { GetSustainability, GetAbout, GetNews, GetLastNews, GetAllNews, GetJob, GetAllJobs, GetPress, GetAllPress } from './about.gql'
export { GetShowroom, GetAllShowrooms, GetDistributor, GetAllDistributors, GetReseller, GetAllResellers, GetStaff, GetAllStaffs, GetContact } from './contact.gql'
export { GetDesigner, GetAllDesigners } from './designer.gql'
export { GetGlobal } from './global.gql'
export { GetIntl } from './intl.gql'
export { GetProduct, GetAllProducts, GetAllProductsLight, GetProductStart, GetProductCategories, GetAllProductsByDesigner } from './product.gql'
export { GetProject, GetAllProjects, GetProjectStart, GetAllProjectTypes, GetBespoke, GetFactoryVisit } from './professional.gql'
export { GetSiteSEO } from './seo.gql'
export { GetStart } from './start.gql'
export { GetFaq, GetAllFaqs, GetAllFaqCategories, GetFaqStart } from './support.gql'
export { GetTaxonomy } from './taxonomy.gql'