query AllProductLightsources($first: IntType = 100, $skip: IntType = 0) {
	allProductLightsources(first: $first, skip: $skip) {
		id
		name
		price
		articleNo
		image {
			...ImageThumbnailFragment
		}
	}
	_allProductLightsourcesMeta {
		count
	}
}
