query Menu {
  designers : allDesigners(first: 100, orderBy: [name_ASC]){
    id
    slug
    name
  }
  products: allProducts(first: 100){
    id
    designer{
      id
    }
  }
  productCategories: allProductCategories{
    id
    name
  }
}
