query Pricelist($locale: SiteLocale!) {
	pricelist(locale: $locale) {
		id
		cover {
			id
			url
		}
		coverIncVat {
			id
			url
		}
		currentPricelist {
			id
			filename
			url
		}
	}
	pricelistFile: pricelist {
		currentPricelist {
			id
			filename
			url
		}
	}
}
