#import "./fragments/ProductFragment.gql"
#import "./fragments/ProductLightFragment.gql"
#import "./fragments/ImageFragment.gql"

query GetProduct($slug: String, $locale: SiteLocale = en) {
	product(locale: $locale, fallbackLocales: [sv, en], filter: {slug: { eq: $slug }}) {
		...ProductFragment
	}
}

query GetAllProducts($locale: SiteLocale = en, $first: IntType = 100, $skip: IntType = 0) {
	products: allProducts(locale: $locale, first: $first, skip: $skip, orderBy: [title_ASC], fallbackLocales: [sv, en]) {
		...ProductFragment
	}
}

query GetAllProductsLight($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	products: allProducts(first: $first, skip: $skip, orderBy: [title_ASC], locale: $locale, fallbackLocales: [sv, en]) {
		...ProductLightFragment
	}
}

query GetAllProductManuals($locale: SiteLocale = en, $first: IntType = 100, $skip: IntType = 0) {
	products: allProducts(locale: $locale, first: $first, skip: $skip, orderBy: [title_ASC], fallbackLocales: [sv, en]) {
		id
    title
    image {
      ...ImageFragment
    }
    family{
      id
      name
    }
    categories{
      id
      name
      position
    }
    mountingInstructions {
      ...FileFragment
    }
    seo: _seoMetaTags {
      attributes
      content
      tag
    }
	}
}
query GetProductStart {
  productStart {
    id
    featured {
      id
      headline
      items {
        ...ProductFragment
      }
    }
  } 
}

query GetProductCategories {
  productCategories : allProductCategories {
    id
    name
    position
  }
}

query GetAllProductsByDesigner($id: ItemId) {
	products: allProducts(filter: {designer: { eq: $id }}) {
		...ProductFragment
	}
}

query GetRelatedProducts($designerId: ItemId, $familyId: ItemId) {
	products: allProducts(
    filter: { 
      OR:[
        {designer: { eq: $designerId }}, 
        {family: { eq: $familyId }}
      ]
    }) {
		...ProductFragment
	}
}

query GetAllProductsByCategory($categoryId: ItemId) {
	products: allProducts(
    filter: { 
      categories: { eq: [$categoryId]}
    }) {
		...ProductFragment
	}
}

