#import "./fragments/ProductFragment.gql"
#import "./fragments/ProductLightFragment.gql"
#import "./fragments/ImageFragment.gql"

query Product($slug: String, $locale: SiteLocale = en) {
	product(locale: $locale, fallbackLocales: [sv, en], filter: {slug: { eq: $slug }}) {
		...ProductFragment
	}
}

query AllProducts($locale: SiteLocale = en, $first: IntType = 100, $skip: IntType = 0) {
	products: allProducts(locale: $locale, first: $first, skip: $skip, orderBy: [title_ASC], fallbackLocales: [sv, en]) {
		...ProductFragment
	}
}

query AllProductsLight($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	products: allProducts(first: $first, skip: $skip, orderBy: [title_ASC], locale: $locale, fallbackLocales: [sv, en]) {
		...ProductLightFragment
	}
}

query AllProductManuals($locale: SiteLocale = en, $first: IntType = 100, $skip: IntType = 0) {
	products: allProducts(locale: $locale, first: $first, skip: $skip, orderBy: [title_ASC], fallbackLocales: [sv, en]) {
		id
    title
    family{
      id
      name
    }
    categories{
      id
      name
      position
    }
    mountingInstructions {
      ...FileFragment
    }
	}
}
query AllProductDownloads($locale: SiteLocale = en, $first: IntType = 100, $skip: IntType = 0) {
	products: allProducts(locale: $locale, first: $first, skip: $skip, orderBy: [title_ASC], fallbackLocales: [sv, en]) {
		image{
      ...ImageThumbnailFragment
    }
    title
    categories{ 
      name
    }
    mountingInstructions {
      ...FileFragment
    }
    pdfFile {
      ...FileFragment
    }
    pdfFiles :_allPdfFileLocales {
      locale
      value {
        ...FileFragment
      }
    }
    bimLink
    lightFile{
      ...FileFragment
    }
    
	}
}
query ProductStart {
  productStart {
    id
    featured {
      id
      headline
      items {
        ...ProductLightFragment
      }
    }
  } 
}

query ProductCategories {
  productCategories : allProductCategories {
    id
    name
    position
  }
}

query AllProductsByDesigner($id: ItemId,  $first: IntType = 100) {
	products: allProducts(first:$first, filter: {designer: { eq: $id }}) {
		...ProductLightFragment
	}
}

query RelatedProducts($designerId: ItemId, $familyId: ItemId,  $first: IntType = 100) {
	relatedProducts: allProducts(
    first: $first,
    filter: { 
      OR:[
        {designer: { eq: $designerId }}, 
        {family: { eq: $familyId }}
      ]
    }) {
		...ProductLightFragment
	}
}

query RelatedProjectsForProduct($productId: ItemId, $first: IntType = 100) {
	relatedProjects: allProjects(
    first: $first,
    filter: { 
      relatedProducts :{ anyIn: [$productId]}
    }) {
		...ProjectLightFragment
	}
}

query AllProductsByCategory($categoryId: ItemId,  $first: IntType = 100) {
	productsByCategory: allProducts(
    first:$first,
    filter: { 
      categories: { eq: [$categoryId]}
    }) {
		...ProductLightFragment
	}
}

