query Project($slug: String) {
	project(filter: { slug: { eq: $slug } }) {
		...ProjectFragment
	}
}

query AllProjects($first: IntType = 100) {
	projects: allProjects(first: $first) {
		...ProjectLightFragment
	}
}

query AllRelatedProjects($projectType: ItemId, $first: IntType = 100) {
	projects: allProjects(first: $first, filter: { projectType: { eq: $projectType } }) {
		...ProjectLightFragment
	}
}

query ProjectStart {
	projectStart {
		id
		intro(markdown: false)
		title
	}
}

query AllProjectTypes {
	projectTypes: allProjectTypes {
		id
		title
		titlePlural
	}
}

query Bespoke {
	bespoke {
		id
		intro(markdown: false)
		outro(markdown: false)
		title
		image {
			...ImageFragment
		}
		examples {
			id
			summary(markdown: false)
			project {
				...ProjectFragment
			}
		}
	}
}

query BespokeThumbnail {
	bespokeThumbnail: bespoke {
		thumbnail {
			...ImageThumbnailFragment
		}
		secondaryThumbnail {
			...ImageThumbnailFragment
		}
	}
}

query FactoryVisit {
	factoryVisit {
		id
		title
		intro(markdown: false)
	}
}

query DownloadsStart {
	downloadsStart {
		id
		intro(markdown: false)
		title
	}
}

query AllCatalogues($first: IntType = 100) {
	catalogues: allCatalogues(first: $first) {
		id
		title
		pdf {
			...FileFragment
		}
		thumbnail {
			...ImageThumbnailFragment
		}
	}
}

query AllColorsAndMaterials($first: IntType = 100) {
	colorMaterials: allColorMaterials(first: $first) {
		id
		image {
			...ImageFragment
		}
		thumb: image {
			...ImageThumbnailFragment
		}
		description
		category {
			id
			category
			categoryPlural
		}
	}
	colorMaterialTypes: allColorMaterialTypes {
		id
		category
		categoryPlural
	}
	colorMaterialIntro {
		id
		intro
	}
}

fragment ProjectFragment on ProjectRecord {
	id
	location
	title
	slug
	bespoke
	projectType {
		id
		title
		titlePlural
	}
	image {
		...ImageFragment
	}
	secondaryImage {
		...ImageFragment
	}
	relatedProducts {
		...ProductFragment
	}
	gallery {
		... on FullwidthImageRecord {
			__typename
			id
			image {
				...ImageFragment
			}
		}
		... on ImageGalleryRecord {
			__typename
			id
			gallery {
				...ImageFragment
			}
		}
		... on TextRecord {
			__typename
			id
			text {
				value
				links {
					__typename
					... on ProductRecord {
						id
						title
						slug
					}
					... on DesignerRecord {
						id
						name
						slug
					}
					... on ProjectRecord {
						id
						title
						slug
					}
				}
			}
		}
		... on TwoColumnImageRecord {
			__typename
			id
			firstImage {
				...ImageMediumFragment
			}
			lastImage {
				...ImageMediumFragment
			}
		}
		... on VideoRecord {
			__typename
			id
			video {
				...ImageFragment
			}
		}
	}
	_seoMetaTags {
		...SEOFragment
	}
}

fragment ProjectLightFragment on ProjectRecord {
	id
	location
	title
	slug
	projectType {
		id
		title
		titlePlural
	}
	image {
		...ImageThumbnailFragment
	}
	secondaryImage {
		...ImageThumbnailFragment
	}
}
