#import "./fragments/ImageFragment.gql"
#import "./fragments/ImageMediumFragment.gql"
#import "./fragments/ImageThumbnailFragment.gql"
#import "./fragments/ProjectFragment.gql"
#import "./fragments/ProjectLightFragment.gql"

query Project($slug: String) {
	project(filter: { slug: { eq: $slug } }) {
		...ProjectFragment
	}
}

query AllProjects($first: IntType = 100) {
	projects: allProjects(first: $first) {
		...ProjectLightFragment
	}
}

query AllRelatedProjects($projectType: ItemId, $first: IntType = 100) {
	projects: allProjects(first: $first, filter: { projectType: { eq: $projectType } }) {
		...ProjectLightFragment
	}
}

query ProjectStart {
	projectStart {
		id
		intro(markdown: false)
		title
	}
}

query AllProjectTypes {
	projectTypes: allProjectTypes {
		id
		title
		titlePlural
	}
}

query Bespoke {
	bespoke {
		id
		intro(markdown: false)
		outro(markdown: false)
		title
		image {
			...ImageFragment
		}
		examples {
			id
			summary(markdown: false)
			project {
				...ProjectFragment
			}
		}
	}
}

query BespokeThumbnail {
	bespokeThumbnail: bespoke {
		thumbnail {
			...ImageThumbnailFragment
		}
		secondaryThumbnail {
			...ImageThumbnailFragment
		}
	}
}

query FactoryVisit {
	factoryVisit {
		id
		title
		intro(markdown: false)
	}
}

query AllCatalogues($first: IntType = 100) {
	catalogues: allCatalogues(first: $first) {
		id
		title
		pdf {
			...FileFragment
		}
		thumbnail {
			...ImageThumbnailFragment
		}
	}
}

query AllColorsAndMaterials($first: IntType = 100) {
	colorMaterials: allColorMaterials(first: $first) {
		id
		image {
			...ImageFragment
		}
		thumb: image {
			...ImageThumbnailFragment
		}
		description
		category {
			id
			category
			categoryPlural
		}
	}
	colorMaterialTypes: allColorMaterialTypes {
		id
		category
		categoryPlural
	}
	colorMaterialIntro {
		id
		intro
	}
}
