
query GetStart {
  start {
    id
    content {
      ... on FeaturedRecord {
        id
      }
      ... on FullscreenImageRecord {
        id
      }
      ... on FullscreenVideoRecord {
        id
      }
      ... on ImageLinkRecord {
        id
      }
    }
  }
}
