#import "./fragments/ProductFragment.gql"
#import "./fragments/DesignerFragment.gql"
#import "./fragments/ImageFragment.gql"

query GetStart {
  start {
    content {
      __typename
      ... on FeaturedRecord {
        id
        headline
        items {
          ...ProductFragment
        }
      }
      ... on FullscreenImageRecord {
        id
        headline
        subHeadline
        image {
          ...ImageFragment
        }
        link{
          ... on ProductRecord{
            ...ProductFragment
          }
          ... on DesignerRecord{
            ...DesignerFragment
          }
        }
      }
      ... on FullscreenVideoRecord {
        id
        link
        linkText
        text
        video {
          ...ImageFragment
        }
      }
      ... on ImageLinkRecord {
        id
        firstImage{
          ...ImageFragment
        }
        firstLink
        firstLinkText
        firstHeadline
        secondImage {
          ...ImageFragment
        }
        secondLink
        secondLinkText
        secondHeadline
      }
    }
  }
}
