#import './fragments/FaqFragment.gql'

query Faq($id: ItemId) {
  faq(filter:{id:{eq:$id}}){
    ...FaqFragment
  }
}

query AllFaqs {
  faqs : allFaqs {
    ...FaqFragment
  }
}

query AllFaqCategories {
  faqCategories: allFaqCategories {
    id
    title
  }
}

query FaqStart {
  faqStart {
    intro(markdown: false)
    id
    title
  }
  faqs: allFaqs {
    ...FaqFragment
  }
}