query Faq($id: ItemId) {
	faq(filter: { id: { eq: $id } }) {
		...FaqFragment
	}
}

query AllFaqs($first: IntType = 100, $skip: IntType = 0) {
	allFaqs(first: $first, skip: $skip) {
		...FaqFragment
	}
	_allFaqsMeta {
		count
	}
}

query AllFaqCategories($first: IntType = 100, $skip: IntType = 0) {
	allFaqCategories(first: $first, skip: $skip) {
		id
		title
	}
	_allFaqCategoriesMeta {
		count
	}
}

query FaqStart {
	faqStart {
		intro(markdown: false)
		id
		title
	}
	faqs: allFaqs(first: 500, skip: 0) {
		...FaqFragment
	}
}

query ManualsIntro {
	manual {
		intro(markdown: false)
		id
		title
	}
}

fragment FaqFragment on FaqRecord {
	updatedAt
	createdAt
	answer
	id
	question
	category {
		id
		title
	}
}

query PrivacyPolicy {
	privacyPolicy {
		__typename
		id
		intro
		title
		policies {
			__typename
			... on PolicyItemRecord {
				__typename
				id
				title
				content {
					blocks
					inlineBlocks
					links
					value
				}
			}
		}
	}
}
