query GetFaq {
  faq {
    updatedAt
    createdAt
    answer
    id
    question
    category {
      id
      title
    }
  }
}
query GetAllFaqs {
  faqs : allFaqs {
    updatedAt
    createdAt
    answer
    id
    question
    category {
      id
      title
    }
  }
}

query GetAllFaqCategories {
  faqCategories: allFaqCategories {
    id
    title
  }
}

query GetFaqStart {
  faqStart {
    intro(markdown: false)
    id
    title
  }
}