query Taxonomy($locale: SiteLocale = sv) {
	designer: allDesigners(locale: $locale) {
		name
		id
		slug
	}
	category: allProductCategories(locale: $locale) {
		id
		name
	}
	color: allProductColors(locale: $locale) {
		id
		name
	}
	connection: allProductConnections(locale: $locale) {
		id
		name
	}
	dimmable: allProductDimmables(locale: $locale) {
		id
		name
	}
	electricalData: allProductElectricals(locale: $locale) {
		id
		name
	}
	family: allProductFamilies(locale: $locale) {
		id
		name
	}
	lightsource: allProductLightsources(locale: $locale) {
		id
		name
		price
		articleNo
	}
	material: allProductMaterials(locale: $locale) {
		id
		name
	}
	mounting: allProductMountings(locale: $locale) {
		id
		name
	}
	socket: allProductSockets(locale: $locale) {
		id
		name
	}
}
