query Cart($id: String, $marketId: String = "1") {
	getCart(id: $id, marketId: $marketId) {
		...CartFragment
	}
}

mutation AddToCart($id: String!, $item: CartItemInputType!, $marketId: String = "1") {
	addToCart(id: $id, item: $item, marketId: $marketId) {
		...CartFragment
	}
}
mutation UpdateCartItem($id: String!, $item: CartItemInputType!, $marketId: String = "1") {
	updateCartItem(id: $id, item: $item, marketId: $marketId) {
		...CartFragment
	}
}

mutation ClearCart($id: String!, $marketId: String = "1") {
	clearCart(id: $id, marketId: $marketId) {
		...CartFragment
	}
}

mutation CompletCart($id: String!) {
	completeCart(id: $id) {
		...CartFragment
	}
}

fragment CartFragment on CartType {
	id
	isCompleted
	freeShipping

	summary {
		shipping {
			feeIncVat
			feeExVat
		}
		total {
			sellingPriceExVat
			sellingPriceIncVat
			vat
			currency {
				name
				symbol
				code
				rate
			}
		}
		subTotal {
			sellingPriceExVat
			sellingPriceIncVat
			vat
			currency {
				name
				symbol
				code
				rate
			}
		}
	}
	items {
		__typename
		id
		skuId
		product {
			...ProductFragment
		}
		totalPrice {
			sellingPriceExVat
			sellingPriceIncVat
			vat
		}
		unitPrice {
			sellingPriceExVat
			sellingPriceIncVat
			currency {
				name
				symbol
				code
				rate
			}
		}
		quantity
		groupKey
	}
}
