query Cart($id: String, $marketId: String = "1") {
	getCart(id: $id, marketId: $marketId) {
		...CartFragment
	}
}

mutation AddToCart($id: String!, $item: CartItemInputType!, $marketId: String = "1") {
	addToCart(id: $id, item: $item, marketId: $marketId) {
		...CartFragment
	}
}
mutation UpdateCartItem($id: String!, $item: CartItemInputType!, $marketId: String = "1") {
	updateCartItem(id: $id, item: $item, marketId: $marketId) {
		...CartFragment
	}
}

mutation ClearCart($id: String!, $marketId: String = "1") {
	clearCart(id: $id, marketId: $marketId) {
		...CartFragment
	}
}

fragment CartFragment on CartType {
	id
	summary {
		total {
			sellingPriceExVat
			currency {
				name
				symbol
				code
				rate
			}
		}
		subTotal {
			sellingPriceExVat
			currency {
				name
				symbol
				code
				rate
			}
		}
	}
	items {
		__typename
		id
		skuId
		product {
			...ProductFragment
		}
		totalPrice {
			sellingPriceExVat
			regularPriceIncVatFormatted
			sellingPriceExVat
		}
		unitPrice {
			sellingPriceExVat
			sellingPriceExVat
			currency {
				name
				symbol
				code
				rate
			}
		}
		quantity
		groupKey
	}
}
