query Checkout($orderId: String!, $cartId: String, $paymentType: PaymentType!) {
	checkout(id: $orderId, cartId: $cartId, paymentType: $paymentType) {
		htmlSnippet
		newCheckoutSession
		completed
		cart {
			id
		}
	}
}
