#import './fragments/CartFragment.gql'
#import './fragments/CartErrorsFragment.gql'


query Cart($id: ID!) {
  cart(id: $id) {
    ...CartFragment
  }
}

mutation CreateCart($cartInput: CartInput) {
  cartCreate(input: $cartInput) {
    cart {
      ...CartFragment
    }
    userErrors {
      ...CartErrorsFragment
    }
  }
}

mutation AddItemToCart($cartId: ID!, $lines: [CartLineInput!]!) {
  cartLinesAdd(cartId: $cartId, lines: $lines) {
    cart {
      ...CartFragment
    }
    userErrors {
      ...CartErrorsFragment
    }
  }
}

mutation RemoveItemFromCart($cartId: ID!, $lineIds: [ID!]!) {
  cartLinesRemove(cartId: $cartId, lineIds: $lineIds) {
    cart {
      ...CartFragment
    }
    userErrors {
      ...CartErrorsFragment
    }
  }
}

mutation UpdateItemFromCart($cartId: ID!, $lines: [CartLineUpdateInput!]!) {
  cartLinesUpdate(cartId: $cartId, lines: $lines) {
    cart {
      ...CartFragment
    }
    userErrors {
      ...CartErrorsFragment
    }
  }
}