query AllShopifyCollections($country: CountryCode = SE, $first: Int = 100) @inContext(country: $country) {
	collections(first: $first) {
		edges {
			node {
				...CollectionFragment
			}
		}
		pageInfo {
			hasNextPage
		}
	}
}

query ShopifyCollection($country: CountryCode = SE, $handle: String, $first: Int = 100) @inContext(country: $country) {
	collection(handle: $handle) {
		id
		handle
		title
		description
		image {
			id
			url
			height
			width
			altText
		}
		products(first: $first) {
			edges {
				node {
					...ProductFragment
				}
			}
		}
	}
}

fragment CollectionFragment on Collection {
	id
	handle
	title
	description
	image {
		id
		url
		height
		width
		altText
	}
}
