#import './fragments/CustomerFragment.gql'

mutation customerCreate($input: CustomerCreateInput!) {
  customerCreate(input: $input) {
    customer {
      ...CustomerFragment
    }
    customerUserErrors {
      code
      field
      message
    }
  }
}

mutation customerAccessTokenCreate($input: CustomerAccessTokenCreateInput!){
  customerAccessTokenCreate(input: $input){
    customerAccessToken {
      accessToken
      expiresAt      
    }
    customerUserErrors {
      code
      field
      message
    }
  }
}