#import './fragments/CustomerFragment.gql'
#import './fragments/CustomerErrorsFragment.gql'
#import './fragments/UserErrorsFragment.gql'

query Customer($accessToken:String!){
  customer(customerAccessToken: $accessToken){
    ...CustomerFragment
  }
}

mutation CustomerCreate($input: CustomerCreateInput!) {
  customerCreate(input: $input) {
    customer {
      ...CustomerFragment
    }
    customerUserErrors {
      code
      field
      message
    }
  }
}

mutation CustomerAccessTokenCreate($input: CustomerAccessTokenCreateInput!){
  customerAccessTokenCreate(input: $input){
    customerAccessToken {
      accessToken
      expiresAt      
    }
    customerUserErrors {
      ...CustomerErrorsFragment
    }
  }
}

mutation CustomerAccessTokenDelete($accessToken: String!){
  customerAccessTokenDelete(customerAccessToken: $accessToken){
    deletedAccessToken
    userErrors {
      ...UserErrorsFragment
    }
  }
}

