query Customer($accessToken: String!) {
	customer(customerAccessToken: $accessToken) {
		...CustomerFragmentLight
	}
}

query CustomerFull($accessToken: String!) {
	customer(customerAccessToken: $accessToken) {
		...CustomerFragment
	}
}

query CustomerOrders($accessToken: String!) {
	customer(customerAccessToken: $accessToken) {
		...CustomerOrderFragment
	}
}

mutation CustomerCreate($input: CustomerCreateInput!) {
	customerCreate(input: $input) {
		customer {
			...CustomerFragment
		}
		customerUserErrors {
			code
			field
			message
		}
	}
}

mutation CustomerAccessTokenCreate($input: CustomerAccessTokenCreateInput!) {
	customerAccessTokenCreate(input: $input) {
		customerAccessToken {
			accessToken
			expiresAt
		}
		customerUserErrors {
			...CustomerErrorsFragment
		}
	}
}

mutation CustomerAccessTokenDelete($accessToken: String!) {
	customerAccessTokenDelete(customerAccessToken: $accessToken) {
		deletedAccessToken
		userErrors {
			...UserErrorsFragment
		}
	}
}

fragment CustomerFragment on Customer {
	id
	createdAt
	updatedAt
	displayName
	firstName
	lastName
	email
	addresses(first: 100) {
		edges {
			node {
				id
				address1
				lastName
				name
				phone
				province
				provinceCode
				zip
				address2
				company
				country
				countryCodeV2
				firstName
				formatted
				formattedArea
			}
		}
	}
	orders(first: 100) {
		edges {
			node {
				id
				fulfillmentStatus
				canceledAt
				lineItems(first: 100) {
					edges {
						node {
							quantity
							title
							variant {
								id
								title
								price {
									amount
									currencyCode
								}
							}
						}
					}
				}
			}
		}
	}
}

fragment CustomerFragmentLight on Customer {
	id
	createdAt
	updatedAt
	firstName
	lastName
	email
}

fragment CustomerOrderFragment on Customer {
	id
	orders(first: 10) {
		edges {
			node {
				id
				fulfillmentStatus
				canceledAt
				cancelReason
				processedAt
				totalPrice {
					amount
					currencyCode
				}
				lineItems(first: 100) {
					edges {
						node {
							quantity
							title
							variant {
								title
								price {
									amount
									currencyCode
								}
							}
						}
					}
				}
			}
		}
	}
}

fragment CustomerErrorsFragment on CustomerUserError {
	__typename
	field
	message
	code
}

fragment UserErrorsFragment on UserError {
	__typename
	field
	message
}
