query Localization($country: CountryCode = SE, $language: LanguageCode = EN)
@inContext(country: $country, language: $language) {
	localization {
		availableCountries {
			currency {
				isoCode
				name
				symbol
			}
			isoCode
			name
			unitSystem
		}
		country {
			currency {
				isoCode
				name
				symbol
			}
			market {
				id
				handle
			}
			isoCode
			name
			unitSystem
		}
	}
}
