#import "./fragments/ShopifyProductFragment.gql"

query AllShopifyProducts($first: Int = 5){
  products(first: $first) {
    edges {
      node {
        ...ShopifyProductFragment
      }
    }
    pageInfo {
      hasNextPage
    }
  }
}

query ShopifyProduct($id : ID!){
  product(id: $id) {
    ...ShopifyProductFragment
  }
}