#import "./ImageMediumFragment.gql"
#import "./SEOFragment.gql"

fragment DesignerFragment on DesignerRecord {
	id
	name
	image {
		...ImageMediumFragment
	}
	description
	slug
	_seoMetaTags {
		...SEOFragment
	}
}
