fragment ImageMediumFragment on FileField {
	id
	mimeType
	url
	title
	customData
	responsiveImage(
		imgixParams: { w: 1600, auto: format }
		sizes: "(max-width: 46.24em) 100vw, 50vw"
	) {
		src
		width
		height
		alt
		base64
		sizes
	}
}
