fragment ImageThumbnailFragment on FileField {
	id
	mimeType
	url
	title
	responsiveImage(
		imgixParams: { w: 800, q: 50, auto: format }
		sizes: "(max-width: 46.24em) 50vw, 25vw"
	) {
		src
		width
		height
		alt
		base64
		sizes
	}
}
