mutation FileUpdate($input: [FileUpdateInput!]!) {
	fileUpdate(files: $input) {
		userErrors {
			code
			field
			message
		}
		files {
			alt
		}
	}
}

mutation FileDelete($id: [ID!]!) {
	fileDelete(fileIds: $id) {
		deletedFileIds
		userErrors {
			code
			field
			message
		}
	}
}

query Files($first: Int = 100, $after: String) {
	files(first: $first, after: $after) {
		edges {
			node {
				id
				alt
			}
		}
		pageInfo {
			hasNextPage
			hasPreviousPage
			endCursor
			startCursor
		}
	}
}
