mutation FileUpdate($input: [FileUpdateInput!]!) {
	fileUpdate(files: $input) {
		userErrors {
			code
			field
			message
		}
		files {
			alt
		}
	}
}

mutation FileDelete($id: [ID!]!) {
	fileDelete(fileIds: $id) {
		deletedFileIds
		userErrors {
			code
			field
			message
		}
	}
}
