query AllPriceLists {
	priceLists(first: 100) {
		nodes {
			...PriceListFragment
		}
	}
}

query PriceList($id: ID!) {
	priceList(id: $id) {
		...PriceListFragment
	}
}

mutation priceListCreate($input: PriceListCreateInput!) {
	priceListCreate(input: $input) {
		priceList {
			...PriceListFragment
		}
		userErrors {
			field
			message
		}
	}
}

mutation PriceListUpdate($id: ID!, $input: PriceListUpdateInput!) {
	priceListUpdate(id: $id, input: $input) {
		priceList {
			...PriceListFragment
		}
		userErrors {
			field
			message
		}
	}
}

mutation PriceListFixedPricesAdd($priceListId: ID!, $prices: [PriceListPriceInput!]!) {
	priceListFixedPricesAdd(priceListId: $priceListId, prices: $prices) {
		prices {
			variant {
				id
			}
		}
		userErrors {
			field
			message
		}
	}
}

mutation PriceListFixedPricesUpdate(
	$priceListId: ID!
	$pricesToAdd: [PriceListPriceInput!]!
	$variantIdsToDelete: [ID!]!
) {
	priceListFixedPricesUpdate(
		priceListId: $priceListId
		pricesToAdd: $pricesToAdd
		variantIdsToDelete: $variantIdsToDelete
	) {
		deletedFixedPriceVariantIds
		priceList {
			...PriceListFragment
		}
		pricesAdded {
			...PriceListPriceFragment
		}
		userErrors {
			field
			message
		}
	}
}

fragment PriceListFragment on PriceList {
	id
	name
	currency
	name
	catalog {
		id
		title
	}
}

fragment PriceListPriceFragment on PriceListPrice {
	originType
	variant {
		...ProductVariantFragment
	}
	price {
		amount
		currencyCode
	}
}
